version: '3.4'

services:
  websaver.api:
    image: websaver:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:SqlConnection=Server=db;Database=Rating;User Id=sa;Password=YourPassword123!;"
    ports:
      - "5000:80"
    depends_on:
      - db
    networks:
      my-project-network:
        ipv4_address: 192.168.77.2

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourPassword123!
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    networks:
      my-project-network:
        ipv4_address: 192.168.77.12

networks:
  my-project-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.77.0/24
          gateway: 192.168.77.1
