version: '3.4'

services:
  websaver.api:
    image: websaver:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:PostgreConnection=Server=db;Port=5432;Database=saver;User Id=postgres;Password=postgres;"
    ports:
      - "5000:80"
    depends_on:
      - db
    networks:
      my-project-network:
        ipv4_address: 192.168.77.2

  db:
    image: postgres:13.11
    environment:
#      - POSTGRES_DB=
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      my-project-network:
        ipv4_address: 192.168.77.12

networks:
  my-project-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.77.0/24
          gateway: 192.168.77.1
