version: '3.4'

services:
  backend:
    image: websaver:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings:PostgreConnection:Host=database;Port=5432;Database=saver;Username=lsodis;Password=6742;
    ports:
      - "5000:80"
    depends_on:
      - database
    networks:
      my-project-network:
        ipv4_address: 192.168.77.2

  database:
    image: postgres:latest
    environment:
      - POSTGRES_DB=saver
      - POSTGRES_USER=lsodis
      - POSTGRES_PASSWORD=6742
    networks:
      my-project-network:
        ipv4_address: 192.168.77.12

networks:
  my-project-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.77.0/24
          gateway: 192.168.77.1